/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis */
        get: operations["analysis_api_v1_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email + password for a session cookie. A wrong email or
         *     password is an indistinguishable 401 (no account-enumeration signal).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session and clear the cookie. Idempotent: safe to
         *     call without a valid session (no error, cookie still cleared).
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create an account and sign the new user in (a session cookie is set),
         *     so the client can move straight into resume onboarding.
         */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List matching active jobs with facet counts and keyset pagination.
         *
         *     Both the count and the rows come from the shared predicate — this is
         *     the endpoint dashboard stats click through to, and its total must
         *     always equal the number the user clicked.
         */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description The current user's profiles only — the query is scoped to the
         *     session, so it can never surface another account's data.
         */
        get: operations["list_profiles_api_v1_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profiles__profile_id__get"];
        /**
         * Put Profile
         * @description Full-document reconcile: id = keep/update, no id = create as
         *     manual, absent = delete. One transaction — the review screen's Save.
         */
        put: operations["put_profile_api_v1_profiles__profile_id__put"];
        post?: never;
        /**
         * Remove Profile
         * @description Delete the profile and its uploaded resume (user-owned data).
         */
        delete: operations["remove_profile_api_v1_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile Matches
         * @description Rank active jobs against this profile (M9). The profile must belong to
         *     the signed-in user (404 otherwise) and be reviewed (409 otherwise —
         *     invariant #9: an unreviewed extraction is not usable). Accepts the same
         *     `JobFilters` the market surface does; the candidate job pool is the
         *     shared predicate, so the counts agree with search.
         */
        get: operations["profile_matches_api_v1_profiles__profile_id__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/reextract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reextract Profile
         * @description Rebuild the profile from the stored resume text, discarding all
         *     edits — an explicit user action (ADR-005), useful after taxonomy
         *     growth. The resume bytes and text are untouched.
         */
        post: operations["reextract_profile_api_v1_profiles__profile_id__reextract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Resume
         * @description Upload a PDF resume: parse, extract, and return the structured
         *     profile in one synchronous call (the pipeline is deterministic rules,
         *     well under a second). The resume and profile are owned by the uploading
         *     user. Re-uploading identical bytes is idempotent and returns the user's
         *     existing profile untouched — edits survive.
         */
        post: operations["upload_resume_api_v1_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Saved Jobs
         * @description The saved-jobs dashboard: each saved job with a live match score,
         *     matched/missing skills, and reasons drawn from the user's most recently
         *     reviewed profile.
         */
        get: operations["get_saved_jobs_api_v1_saved_jobs_get"];
        put?: never;
        /**
         * Create Saved Job
         * @description Save a job. Idempotent; returns the updated saved-id set.
         */
        post: operations["create_saved_job_api_v1_saved_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-jobs/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Saved Job Ids
         * @description The ids the user has saved — for rendering the Save button's state in
         *     search and job detail. Saved jobs stay in search; this only toggles UI.
         */
        get: operations["get_saved_job_ids_api_v1_saved_jobs_ids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Saved Job
         * @description Unsave a job. Idempotent.
         */
        delete: operations["delete_saved_job_api_v1_saved_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill Detail */
        get: operations["skill_detail_api_v1_skills__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisHeader */
        AnalysisHeader: {
            /** Analyzed Jobs */
            analyzed_jobs: number;
            /** Low Confidence */
            low_confidence: boolean;
            /** Min Sample Size */
            min_sample_size: number;
            /** Salary Disclosed */
            salary_disclosed: number;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Arrangements */
            arrangements: components["schemas"]["DistributionBucket"][];
            /** Categories */
            categories: components["schemas"]["CategoryStats"][];
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Data Version */
            data_version: string;
            /** Experience Levels */
            experience_levels: components["schemas"]["DistributionBucket"][];
            filters: components["schemas"]["JobFilters"];
            header: components["schemas"]["AnalysisHeader"];
            salary: components["schemas"]["SalarySummary"];
            /** Top Companies */
            top_companies: components["schemas"]["CompanyStat"][];
        };
        /** Body_upload_resume_api_v1_resumes_post */
        Body_upload_resume_api_v1_resumes_post: {
            /** File */
            file: string;
        };
        /** CategoryStats */
        CategoryStats: {
            /** Category */
            category: string;
            /** Distinct Technologies */
            distinct_technologies: number;
            /** Label */
            label: string;
            /** Technologies */
            technologies: components["schemas"]["TechnologyStat"][];
        };
        /**
         * CoOccurrenceStat
         * @description A technology that appears alongside this skill more often than its
         *     base rate in the same scope predicts (lift >= the floor).
         */
        CoOccurrenceStat: {
            /** Baseline Share */
            baseline_share: number;
            /** Category */
            category: string;
            /** Count */
            count: number;
            /** Lift */
            lift: number;
            /** Name */
            name: string;
            /** Share Given Tech */
            share_given_tech: number;
            /** Slug */
            slug: string;
        };
        /** CompanyStat */
        CompanyStat: {
            /** Count */
            count: number;
            /** Name */
            name: string;
        };
        /** DistributionBucket */
        DistributionBucket: {
            /** Count */
            count: number;
            /** Share */
            share: number;
            /** Value */
            value: string;
        };
        /** EducationIn */
        EducationIn: {
            /** Degree Raw */
            degree_raw?: string | null;
            /** End Year */
            end_year?: number | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Id */
            id?: number | null;
            /** Institution */
            institution?: string | null;
            /** Start Year */
            start_year?: number | null;
        };
        /** EducationOut */
        EducationOut: {
            /** Degree Level */
            degree_level: string | null;
            /** Degree Raw */
            degree_raw: string | null;
            /** End Year */
            end_year: number | null;
            /** Evidence End */
            evidence_end: number | null;
            /** Evidence Start */
            evidence_start: number | null;
            /** Field Of Study */
            field_of_study: string | null;
            /** Id */
            id: number;
            /** Institution */
            institution: string | null;
            /** Origin */
            origin: string;
            /** Position */
            position: number;
            /** Start Year */
            start_year: number | null;
        };
        /** ExperienceAlignmentOut */
        ExperienceAlignmentOut: {
            /** Candidate Level */
            candidate_level: string | null;
            /** Candidate Years */
            candidate_years: number | null;
            /** Job Level */
            job_level: string | null;
            /** Job Years */
            job_years: number | null;
            /** Verdict */
            verdict: string;
        };
        /** ExperienceIn */
        ExperienceIn: {
            /** Company */
            company?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Id */
            id?: number | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /** Start Date */
            start_date?: string | null;
            /** Summary */
            summary?: string | null;
            /** Title Raw */
            title_raw: string;
        };
        /** ExperienceOut */
        ExperienceOut: {
            /** Canonical Title Id */
            canonical_title_id: number | null;
            /** Company */
            company: string | null;
            /** End Date */
            end_date: string | null;
            /** Evidence End */
            evidence_end: number | null;
            /** Evidence Start */
            evidence_start: number | null;
            /** Id */
            id: number;
            /** Is Current */
            is_current: boolean;
            /** Level */
            level: string | null;
            /** Origin */
            origin: string;
            /** Position */
            position: number;
            /** Start Date */
            start_date: string | null;
            /** Summary */
            summary: string | null;
            /** Title Raw */
            title_raw: string;
        };
        /** FacetBucket */
        FacetBucket: {
            /** Count */
            count: number;
            /** Share */
            share: number;
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetail */
        JobDetail: {
            /** Apply Url */
            apply_url: string | null;
            /** Arrangement */
            arrangement: string | null;
            /** Canonical Title */
            canonical_title: string | null;
            /** Canonical Title Slug */
            canonical_title_slug: string | null;
            /** Company Name */
            company_name: string;
            /** Description Html */
            description_html: string | null;
            /** Description Text */
            description_text: string | null;
            /** Employment Type */
            employment_type: string | null;
            /** Experience Level */
            experience_level: string | null;
            /** Id */
            id: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Locations */
            locations: components["schemas"]["JobLocationOut"][];
            /** Posted At */
            posted_at: string | null;
            salary: components["schemas"]["SalaryOut"];
            /** Sections */
            sections: components["schemas"]["JobSectionOut"][];
            source: components["schemas"]["SourceOut"];
            /** Status */
            status: string;
            /** Technologies */
            technologies: components["schemas"]["JobTechnologyOut"][];
            /** Title Raw */
            title_raw: string;
            /** Years Of Experience */
            years_of_experience: number | null;
        };
        /**
         * JobFilters
         * @description Everything is optional; the empty filter means the national market.
         */
        JobFilters: {
            /** Arrangement */
            arrangement?: ("onsite" | "hybrid" | "remote") | null;
            /** Experience Level */
            experience_level?: ("entry" | "mid" | "senior" | "staff_plus") | null;
            /** Location */
            location?: string | null;
            /** Q */
            q?: string | null;
            /**
             * Radius Miles
             * @default 50
             */
            radius_miles: number;
            /** Salary Min */
            salary_min?: number | null;
            /**
             * Technologies
             * @default []
             */
            technologies: string[];
            /** Title */
            title?: string | null;
        };
        /** JobListItem */
        JobListItem: {
            /** Apply Url */
            apply_url: string | null;
            /** Company Name */
            company_name: string;
            /** Id */
            id: number;
            /** Locations */
            locations: components["schemas"]["JobLocationOut"][];
            /** Posted At */
            posted_at: string | null;
            /** Title Raw */
            title_raw: string;
        };
        /** JobListResponse */
        JobListResponse: {
            facets: components["schemas"]["SearchFacets"];
            /** Items */
            items: components["schemas"]["JobListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Relaxations
             * @default []
             */
            relaxations: components["schemas"]["RelaxationOption"][];
            /**
             * Sort
             * @enum {string}
             */
            sort: "recency" | "salary" | "relevance";
            /** Total */
            total: number;
        };
        /** JobLocationOut */
        JobLocationOut: {
            /** Is Remote */
            is_remote: boolean;
            /** Raw Text */
            raw_text: string;
        };
        /** JobMatchOut */
        JobMatchOut: {
            /** Components */
            components: components["schemas"]["ScoreComponentOut"][];
            experience: components["schemas"]["ExperienceAlignmentOut"];
            job: components["schemas"]["MatchJobSummary"];
            /** Matched Skills */
            matched_skills: components["schemas"]["MatchSkillOut"][];
            /** Missing Skills */
            missing_skills: components["schemas"]["MatchSkillOut"][];
            /** Reasons */
            reasons: string[];
            /** Score */
            score: number;
            title: components["schemas"]["TitleAlignmentOut"];
        };
        /** JobSectionOut */
        JobSectionOut: {
            /** End Offset */
            end_offset: number;
            /** Kind */
            kind: string;
            /** Start Offset */
            start_offset: number;
        };
        /** JobTechnologyOut */
        JobTechnologyOut: {
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /** Evidence Snippet */
            evidence_snippet: string;
            /** Evidence Start */
            evidence_start: number;
            /** Name */
            name: string;
            /** Requirement Level */
            requirement_level: string;
            /** Slug */
            slug: string;
        };
        /** LocationOption */
        LocationOption: {
            /** Job Count */
            job_count: number;
            /** Label */
            label: string;
            /** Slug */
            slug: string;
        };
        /**
         * LoginRequest
         * @description Login does not re-validate password length: complexity rules change
         *     over time and must never lock an existing account out of signing in.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MatchJobSummary
         * @description Enough of a job to render and link a match card. Deliberately no
         *     description: matches never serve posting text — the job-detail endpoint
         *     does, under the display-policy gate.
         */
        MatchJobSummary: {
            /** Apply Url */
            apply_url: string | null;
            /** Arrangement */
            arrangement: string | null;
            /** Canonical Title */
            canonical_title: string | null;
            /** Canonical Title Slug */
            canonical_title_slug: string | null;
            /** Company Name */
            company_name: string;
            /** Experience Level */
            experience_level: string | null;
            /** Id */
            id: number;
            /** Locations */
            locations: components["schemas"]["JobLocationOut"][];
            /** Posted At */
            posted_at: string | null;
            salary: components["schemas"]["SalaryOut"];
            /** Title Raw */
            title_raw: string;
        };
        /**
         * MatchProfileSummary
         * @description The candidate side of the match, for context and honesty: how many
         *     skills actually join the taxonomy, which title families were matched
         *     on, and the derived seniority the experience component used.
         */
        MatchProfileSummary: {
            /** Experience Level */
            experience_level: string | null;
            /** Full Name */
            full_name: string | null;
            /** Highest Degree */
            highest_degree: string | null;
            /** Id */
            id: number;
            /** Matched Skill Count */
            matched_skill_count: number;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Title Families */
            title_families: string[];
            /** Unmapped Skill Count */
            unmapped_skill_count: number;
            /** Years Experience */
            years_experience: number | null;
        };
        /** MatchSkillOut */
        MatchSkillOut: {
            /** Name */
            name: string;
            /** Requirement Level */
            requirement_level: string;
            /** Slug */
            slug: string;
        };
        /**
         * MatchWeights
         * @description The nominal component weights, surfaced so the ranking is legible.
         */
        MatchWeights: {
            /** Experience */
            experience: number;
            /** Skills */
            skills: number;
            /** Title */
            title: number;
        };
        /**
         * MetaResponse
         * @description Everything the filter UI needs to render its options.
         */
        MetaResponse: {
            /** Data Version */
            data_version: string;
            /** Locations */
            locations: components["schemas"]["LocationOption"][];
            /** Technologies */
            technologies: components["schemas"]["TechnologyOption"][];
            /** Titles */
            titles: components["schemas"]["TitleOption"][];
        };
        /** ProfileDetail */
        ProfileDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Education */
            education: components["schemas"]["EducationOut"][];
            /** Email */
            email: string | null;
            /** Experiences */
            experiences: components["schemas"]["ExperienceOut"][];
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at: string;
            /** Extractor Version */
            extractor_version: number;
            /** Full Name */
            full_name: string | null;
            /** Id */
            id: number;
            /** Phone */
            phone: string | null;
            resume: components["schemas"]["ResumeOut"];
            /** Reviewed At */
            reviewed_at: string | null;
            /** Skills */
            skills: components["schemas"]["SkillOut"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfileListItem */
        ProfileListItem: {
            /** Email */
            email: string | null;
            /** Experience Count */
            experience_count: number;
            /** Filename */
            filename: string;
            /** Full Name */
            full_name: string | null;
            /** Id */
            id: number;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Skill Count */
            skill_count: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** ProfileListResponse */
        ProfileListResponse: {
            /** Items */
            items: components["schemas"]["ProfileListItem"][];
        };
        /** ProfileMatchesResponse */
        ProfileMatchesResponse: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            filters: components["schemas"]["JobFilters"];
            /** Matched Jobs */
            matched_jobs: number;
            /** Matches */
            matches: components["schemas"]["JobMatchOut"][];
            profile: components["schemas"]["MatchProfileSummary"];
            /** Returned */
            returned: number;
            /** Total Active Jobs */
            total_active_jobs: number;
            weights: components["schemas"]["MatchWeights"];
        };
        /**
         * ProfileUpdate
         * @description Full-document replacement. `reviewed` is the document state, not an
         *     event: true sets reviewed_at (now, if not already set), false clears
         *     it — editing after review naturally un-reviews by sending false.
         */
        ProfileUpdate: {
            /** Education */
            education: components["schemas"]["EducationIn"][];
            /** Email */
            email?: string | null;
            /** Experiences */
            experiences: components["schemas"]["ExperienceIn"][];
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Skills */
            skills: components["schemas"]["SkillIn"][];
        };
        /**
         * RelaxationOption
         * @description One honest way out of a zero-result search: what would change,
         *     and how many jobs that buys. Never applied server-side.
         */
        RelaxationOption: {
            /** Count */
            count: number;
            /** Description */
            description: string;
            filters: components["schemas"]["JobFilters"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "radius" | "salary" | "technology";
        };
        /** ResumeOut */
        ResumeOut: {
            /** Extracted Text */
            extracted_text: string | null;
            /** File Size */
            file_size: number;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Page Count */
            page_count: number | null;
            /** Parser Name */
            parser_name: string | null;
            /** Parser Version */
            parser_version: number | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * SalaryOut
         * @description Both representations, deliberately: raw for honest display
         *     ('$60/hr'), normalized annual USD for anything comparative.
         */
        SalaryOut: {
            /** Annual Max */
            annual_max: string | null;
            /** Annual Min */
            annual_min: string | null;
            /** Currency */
            currency: string | null;
            /** Max Amount */
            max_amount: string | null;
            /** Min Amount */
            min_amount: string | null;
            /** Period */
            period: string | null;
        };
        /** SalarySummary */
        SalarySummary: {
            /** Disclosed Count */
            disclosed_count: number;
            /** Median */
            median: number | null;
            /** P25 */
            p25: number | null;
            /** P75 */
            p75: number | null;
        };
        /**
         * SavedJobIdsResponse
         * @description The ids the current user has saved — the search/detail UIs use this to
         *     render the Save button's saved state without leaking anything else.
         */
        SavedJobIdsResponse: {
            /** Job Ids */
            job_ids: number[];
        };
        /**
         * SavedJobMatch
         * @description The M9 match for a saved job, minus the job (which the card already
         *     holds). Present only when the user has a reviewed profile to match
         *     against; `score` may be 0 for a saved job with no overlap — a saved job
         *     is always explained, never dropped.
         */
        SavedJobMatch: {
            /** Components */
            components: components["schemas"]["ScoreComponentOut"][];
            experience: components["schemas"]["ExperienceAlignmentOut"];
            /** Matched Skills */
            matched_skills: components["schemas"]["MatchSkillOut"][];
            /** Missing Skills */
            missing_skills: components["schemas"]["MatchSkillOut"][];
            /** Reasons */
            reasons: string[];
            /** Score */
            score: number;
            title: components["schemas"]["TitleAlignmentOut"];
        };
        /** SavedJobOut */
        SavedJobOut: {
            job: components["schemas"]["MatchJobSummary"];
            match: components["schemas"]["SavedJobMatch"] | null;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
        };
        /** SavedJobRequest */
        SavedJobRequest: {
            /** Job Id */
            job_id: number;
        };
        /** SavedJobsResponse */
        SavedJobsResponse: {
            /** Items */
            items: components["schemas"]["SavedJobOut"][];
            profile: components["schemas"]["MatchProfileSummary"] | null;
            /** Profile Id */
            profile_id: number | null;
        };
        /** ScoreComponentOut */
        ScoreComponentOut: {
            /** Applicable */
            applicable: boolean;
            /** Contribution */
            contribution: number;
            /** Detail */
            detail: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Score */
            score: number | null;
            /** Weight */
            weight: number;
        };
        /**
         * SearchFacets
         * @description Counts over the full matching set, not just the returned page.
         */
        SearchFacets: {
            /** Arrangements */
            arrangements: components["schemas"]["FacetBucket"][];
            /** Experience Levels */
            experience_levels: components["schemas"]["FacetBucket"][];
        };
        /** SignupRequest */
        SignupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** SkillDetailResponse */
        SkillDetailResponse: {
            /** Arrangements */
            arrangements: components["schemas"]["DistributionBucket"][];
            /** Co Occurring */
            co_occurring: components["schemas"]["CoOccurrenceStat"][];
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Data Version */
            data_version: string;
            /** Experience Levels */
            experience_levels: components["schemas"]["DistributionBucket"][];
            filters: components["schemas"]["JobFilters"];
            header: components["schemas"]["SkillHeader"];
            /** Requirement Levels */
            requirement_levels: components["schemas"]["DistributionBucket"][];
            salary: components["schemas"]["SkillSalary"];
            trend: components["schemas"]["SkillTrend"];
        };
        /** SkillHeader */
        SkillHeader: {
            /** Analyzed Jobs */
            analyzed_jobs: number;
            /** Category */
            category: string;
            /** Jobs With Tech */
            jobs_with_tech: number;
            /** Low Confidence */
            low_confidence: boolean;
            /** Min Sample Size */
            min_sample_size: number;
            /** Name */
            name: string;
            /** Share */
            share: number;
            /** Slug */
            slug: string;
        };
        /**
         * SkillIn
         * @description Keep an existing skill (id) or add a manual one (label, optionally
         *     mapped to a taxonomy slug so it stays matchable).
         */
        SkillIn: {
            /** Id */
            id?: number | null;
            /** Label */
            label?: string | null;
            /** Technology Slug */
            technology_slug?: string | null;
        };
        /** SkillOut */
        SkillOut: {
            /** Confidence */
            confidence: number | null;
            /** Evidence Snippet */
            evidence_snippet: string | null;
            /** Evidence Start */
            evidence_start: number | null;
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Occurrences */
            occurrences: number;
            /** Origin */
            origin: string;
            /** Technology Id */
            technology_id: number | null;
        };
        /**
         * SkillSalary
         * @description Percentiles over disclosed-salary jobs with this skill, plus the
         *     all-jobs national baseline the delta is measured against.
         */
        SkillSalary: {
            /** Delta Vs National */
            delta_vs_national: number | null;
            /** Disclosed Count */
            disclosed_count: number;
            /** Median */
            median: number | null;
            /** National Disclosed Count */
            national_disclosed_count: number;
            /** National Median */
            national_median: number | null;
            /** P25 */
            p25: number | null;
            /** P75 */
            p75: number | null;
        };
        /** SkillTrend */
        SkillTrend: {
            /** Days Observed */
            days_observed: number;
            /** Geo Slug */
            geo_slug: string;
            /** Min Days */
            min_days: number;
            /** Points */
            points: components["schemas"]["TrendPoint"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "collecting_history";
        };
        /** SourceOut */
        SourceOut: {
            /** Attribution Text */
            attribution_text: string | null;
            /** Attribution Url */
            attribution_url: string | null;
            /** Display Policy */
            display_policy: string;
            /** Name */
            name: string;
        };
        /** TechnologyOption */
        TechnologyOption: {
            /** Category */
            category: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** TechnologyStat */
        TechnologyStat: {
            /** Count */
            count: number;
            /** Name */
            name: string;
            /** Required Count */
            required_count: number;
            /** Share */
            share: number;
            /** Slug */
            slug: string;
        };
        /** TitleAlignmentOut */
        TitleAlignmentOut: {
            /** Job Title */
            job_title: string | null;
            /** Job Title Slug */
            job_title_slug: string | null;
            /** Matched */
            matched: boolean | null;
        };
        /** TitleOption */
        TitleOption: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Job Count */
            job_count: number;
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analysis_api_v1_analysis_get: {
        parameters: {
            query?: {
                /** @description Free-text query (websearch syntax) */
                q?: string | null;
                /** @description Canonical title family slug */
                title?: string | null;
                /** @description City slug, e.g. san-francisco-ca */
                location?: string | null;
                radius_miles?: number;
                /** @description Technology slugs (AND) */
                tech?: string[];
                arrangement?: ("onsite" | "hybrid" | "remote") | null;
                experience_level?: ("entry" | "mid" | "senior" | "staff_plus") | null;
                /** @description Annual USD floor */
                salary_min?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                sort?: "recency" | "salary" | "relevance";
                /** @description Opaque keyset cursor from a previous page */
                cursor?: string | null;
                /** @description Free-text query (websearch syntax) */
                q?: string | null;
                /** @description Canonical title family slug */
                title?: string | null;
                /** @description City slug, e.g. san-francisco-ca */
                location?: string | null;
                radius_miles?: number;
                /** @description Technology slugs (AND) */
                tech?: string[];
                arrangement?: ("onsite" | "hybrid" | "remote") | null;
                experience_level?: ("entry" | "mid" | "senior" | "staff_plus") | null;
                /** @description Annual USD floor */
                salary_min?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    list_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
        };
    };
    get_profile_api_v1_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_api_v1_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_profile_api_v1_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_matches_api_v1_profiles__profile_id__matches_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Free-text query (websearch syntax) */
                q?: string | null;
                /** @description Canonical title family slug */
                title?: string | null;
                /** @description City slug, e.g. san-francisco-ca */
                location?: string | null;
                radius_miles?: number;
                /** @description Technology slugs (AND) */
                tech?: string[];
                arrangement?: ("onsite" | "hybrid" | "remote") | null;
                experience_level?: ("entry" | "mid" | "senior" | "staff_plus") | null;
                /** @description Annual USD floor */
                salary_min?: number | null;
            };
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileMatchesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reextract_profile_api_v1_profiles__profile_id__reextract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_v1_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_v1_resumes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_saved_jobs_api_v1_saved_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobsResponse"];
                };
            };
        };
    };
    create_saved_job_api_v1_saved_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobIdsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_saved_job_ids_api_v1_saved_jobs_ids_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobIdsResponse"];
                };
            };
        };
    };
    delete_saved_job_api_v1_saved_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skill_detail_api_v1_skills__slug__get: {
        parameters: {
            query?: {
                /** @description Free-text query (websearch syntax) */
                q?: string | null;
                /** @description Canonical title family slug */
                title?: string | null;
                /** @description City slug, e.g. san-francisco-ca */
                location?: string | null;
                radius_miles?: number;
                /** @description Technology slugs (AND) */
                tech?: string[];
                arrangement?: ("onsite" | "hybrid" | "remote") | null;
                experience_level?: ("entry" | "mid" | "senior" | "staff_plus") | null;
                /** @description Annual USD floor */
                salary_min?: number | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
