"""PDF → text extraction for uploaded resumes (M7).

Fixtures are committed PDFs under tests/fixtures/resumes/ (regenerated by
generate_fixtures.py, dev-only). The parser's contract: deterministic
text, typed loud failures for anything that can't become resume text.
"""

from pathlib import Path

import pytest

from app.profile.pdf import (
    EncryptedPdfError,
    NotAPdfError,
    NoTextError,
    parse_pdf,
)

FIXTURES = Path(__file__).parent / "fixtures" / "resumes"


def _load(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


def test_extracts_single_column_resume():
    parsed = parse_pdf(_load("alex_chen.pdf"))
    assert parsed.page_count == 1
    # Header, an experience entry with its date line, and education all
    # survive extraction on their own lines (line structure is what the
    # downstream section/entry parsers key on).
    lines = parsed.text.split("\n")
    assert lines[0] == "Alex Chen"
    assert "San Francisco, CA | alex.chen@example.com | (415) 555-0100" in lines
    assert "Senior Software Engineer, Wavelength Analytics" in lines
    assert "Mar 2022 - Present" in lines
    assert "University of California, Berkeley" in lines


def test_extraction_is_deterministic():
    data = _load("alex_chen.pdf")
    assert parse_pdf(data).text == parse_pdf(data).text


def test_text_has_no_trailing_whitespace_or_blank_runs():
    text = parse_pdf(_load("alex_chen.pdf")).text
    for line in text.split("\n"):
        assert line == line.rstrip()
    assert "\n\n\n" not in text
    assert not text.startswith("\n") and not text.endswith("\n")


def test_blank_pdf_rejected_as_no_text():
    with pytest.raises(NoTextError):
        parse_pdf(_load("blank.pdf"))


def test_encrypted_pdf_rejected():
    with pytest.raises(EncryptedPdfError):
        parse_pdf(_load("encrypted.pdf"))


def test_non_pdf_bytes_rejected():
    with pytest.raises(NotAPdfError):
        parse_pdf(b"just some text, definitely not a pdf")


def test_corrupt_pdf_rejected():
    # Valid magic header, garbage body: pypdf's failure is wrapped into
    # the same typed error as a wrong file type.
    with pytest.raises(NotAPdfError):
        parse_pdf(b"%PDF-1.7\nthis is not actually a pdf body")
