"""analytics derived tables

Revision ID: 74bc1114f91e
Revises: 794f5dfce01e
Create Date: 2026-07-19 02:24:39.814018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74bc1114f91e'
down_revision: Union[str, Sequence[str], None] = '794f5dfce01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key', name=op.f('pk_analysis_cache'))
    )
    op.create_table('pipeline_meta',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_pipeline_meta'))
    )
    op.create_table('snapshot_runs',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('active_jobs', sa.Integer(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_date', name=op.f('pk_snapshot_runs'))
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('canonical_title_id', sa.Integer(), nullable=True),
    sa.Column('geo_slug', sa.String(), nullable=False),
    sa.Column('job_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_title_id'], ['canonical_titles.id'], name=op.f('fk_market_snapshots_canonical_title_id_canonical_titles')),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_market_snapshots_technology_id_technologies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots')),
    sa.UniqueConstraint('snapshot_date', 'technology_id', 'canonical_title_id', 'geo_slug', name=op.f('uq_market_snapshots_snapshot_date'), postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_market_snapshots_tech_geo', 'market_snapshots', ['technology_id', 'geo_slug', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_snapshots_tech_geo', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('snapshot_runs')
    op.drop_table('pipeline_meta')
    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
