"""extraction tables and job extraction columns

Revision ID: 794f5dfce01e
Revises: 396038724309
Create Date: 2026-07-19 00:25:57.720146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794f5dfce01e'
down_revision: Union[str, Sequence[str], None] = '396038724309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_titles')),
    sa.UniqueConstraint('slug', name=op.f('uq_canonical_titles_slug'))
    )
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technologies')),
    sa.UniqueConstraint('slug', name=op.f('uq_technologies_slug'))
    )
    op.create_index(op.f('ix_technologies_category'), 'technologies', ['category'], unique=False)
    op.create_table('technology_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('cased', sa.String(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('require_context', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_technology_aliases_technology_id_technologies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technology_aliases')),
    sa.UniqueConstraint('alias', name=op.f('uq_technology_aliases_alias'))
    )
    op.create_table('title_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_title_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_title_id'], ['canonical_titles.id'], name=op.f('fk_title_aliases_canonical_title_id_canonical_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_aliases')),
    sa.UniqueConstraint('alias', name=op.f('uq_title_aliases_alias'))
    )
    op.create_table('job_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_sections_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sections'))
    )
    op.create_index(op.f('ix_job_sections_job_id'), 'job_sections', ['job_id'], unique=False)
    op.create_table('job_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('requirement_level', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(), nullable=False),
    sa.Column('extractor_version', sa.Integer(), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=False),
    sa.Column('evidence_start', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_technologies_job_id_jobs')),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_job_technologies_technology_id_technologies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_technologies')),
    sa.UniqueConstraint('job_id', 'technology_id', name=op.f('uq_job_technologies_job_id'))
    )
    op.create_index(op.f('ix_job_technologies_job_id'), 'job_technologies', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_technologies_technology_id'), 'job_technologies', ['technology_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('example_context', sa.Text(), nullable=True),
    sa.Column('example_job_id', sa.Integer(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['example_job_id'], ['jobs.id'], name=op.f('fk_review_queue_example_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue')),
    sa.UniqueConstraint('kind', 'value', name=op.f('uq_review_queue_kind'))
    )
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    op.add_column('jobs', sa.Column('canonical_title_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('description_text', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('extractor_version', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_canonical_title_id'), 'jobs', ['canonical_title_id'], unique=False)
    op.create_index(op.f('ix_jobs_extractor_version'), 'jobs', ['extractor_version'], unique=False)
    op.create_foreign_key(op.f('fk_jobs_canonical_title_id_canonical_titles'), 'jobs', 'canonical_titles', ['canonical_title_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_jobs_canonical_title_id_canonical_titles'), 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_extractor_version'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_canonical_title_id'), table_name='jobs')
    op.drop_column('jobs', 'extracted_at')
    op.drop_column('jobs', 'extractor_version')
    op.drop_column('jobs', 'years_of_experience')
    op.drop_column('jobs', 'description_text')
    op.drop_column('jobs', 'canonical_title_id')
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_job_technologies_technology_id'), table_name='job_technologies')
    op.drop_index(op.f('ix_job_technologies_job_id'), table_name='job_technologies')
    op.drop_table('job_technologies')
    op.drop_index(op.f('ix_job_sections_job_id'), table_name='job_sections')
    op.drop_table('job_sections')
    op.drop_table('title_aliases')
    op.drop_table('technology_aliases')
    op.drop_index(op.f('ix_technologies_category'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_table('canonical_titles')
    # ### end Alembic commands ###
